apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: octopilot-actions
build:
  artifacts:
    - image: ghcr.io/octopilot/actions/release
      context: .
      docker:
        dockerfile: release/Dockerfile
