name: 'Previous Tag'
description: 'Get the previous git tag (for changelog generation).'
inputs: 
  fallback:
    description: 'Value to return if no previous tag is found (e.g. 0.0.0 or empty).'
    required: false
    default: ''
outputs:
  tag:
    description: 'The previous tag found.'
    value: ${{ steps.find.outputs.tag }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/octopilot/actions/previous-tag:latest'
  env:
    INPUT_FALLBACK: ${{ inputs.fallback }}
