name: 'Bump Version'
description: 'Bump semantic version in Go or Rust projects.'
inputs:
  mode:
    description: 'Language mode (go, rust, maven, gradle, node, python, dotnet, text)'
    required: false
    default: 'go'
  bump:
    description: 'Bump type (major, minor, patch)'
    required: false
    default: 'patch'
  file:
    description: 'Path to version file (default: internal/cmd/version.go for go, Cargo.toml for rust)'
    required: false
outputs:
  version:
    description: 'The new version'
  old_version:
    description: 'The previous version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_MODE: ${{ inputs.mode }}
    INPUT_BUMP: ${{ inputs.bump }}
    INPUT_FILE: ${{ inputs.file }}
