name: 'Bump Version'
description: 'Bump semantic version in Go or Rust projects.'
inputs:
  mode:
    description: 'Language mode (go, rust, maven, gradle, node, python, dotnet, text)'
    required: false
    default: 'go'
  bump:
    description: 'Bump type (major, minor, patch)'
    required: false
    default: 'patch'
  file:
    description: 'Path to version file (default: internal/cmd/version.go for go, Cargo.toml for rust)'
    required: false
outputs:
  version:
    description: 'The new version'
    value: ${{ steps.bump.outputs.version }}
  old_version:
    description: 'The previous version'
    value: ${{ steps.bump.outputs.old_version }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: pip install ${{ github.action_path }}/../common

    - name: Bump Version
      id: bump
      shell: bash
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_BUMP: ${{ inputs.bump }}
        INPUT_FILE: ${{ inputs.file }}
      run: python ${{ github.action_path }}/bump_version.py
