name: 'Lint'
description: >
  Runs pre-commit linting against the workspace. Language toolchains (Go, Rust,
  Node, Python, Java) are set up conditionally based on the languages detected
  in the pipeline-context produced by detect-contexts.

# ── Language-specific gotchas ────────────────────────────────────────────────
#
# Go — golangci-lint timeout
#   golangci-lint defaults to a 1-minute timeout. Projects with large vendor
#   trees (e.g. those that vendor Skaffold, pack, or go-containerregistry) will
#   hit "context deadline exceeded" / exit code 4 on cold CI runners.
#   Fix: add a .golangci.yml at the repo root with a longer timeout:
#
#     run:
#       timeout: 10m
#
#   The pre-commit golangci-lint hook reads this file automatically.
#
# Go — golangci-lint Go version mismatch
#   If golangci-lint was compiled with an older Go than the project's go.mod
#   `go` directive specifies, it exits with:
#     "the Go language version (goX.Y) used to build golangci-lint is lower
#      than the targeted Go version (X.Y.Z)"
#   Fix: pin the pre-commit rev to a golangci-lint release that was built with
#   Go >= your project's go.mod version, and keep your local install in sync:
#
#     # In .pre-commit-config.yaml
#     - repo: https://github.com/golangci/golangci-lint
#       rev: v1.64.8   # must be built with Go >= go.mod's `go` directive
#
#     # Local install (run once after cloning)
#     GOVERSION=$(grep '^go ' go.mod | awk '{print $2}')
#     GOTOOLCHAIN="go${GOVERSION}" go install \
#       github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#
# ── Future gotchas ───────────────────────────────────────────────────────────
# Add new entries here as they are discovered while dogfooding this action
# across different language stacks and CI environments.

inputs:
  pipeline-context:
    description: >
      Consolidated CI context object (JSON) produced by detect-contexts.
      Used to determine which language toolchains to set up before running
      pre-commit so that language-specific hooks (rustfmt, golangci-lint, etc.)
      can execute successfully.
    required: true

runs:
  using: "composite"
  steps:
    # ── Parse JSON into individual step outputs ───────────────────────────────
    # fromJson() is not permitted in composite action step `if:` conditions, so
    # we extract all fields here and reference `steps.ctx.outputs.*` below.
    - name: Parse context
      id: ctx
      shell: bash
      env:
        PIPELINE_CONTEXT: ${{ inputs['pipeline-context'] }}
      run: |
        has()  { echo "$PIPELINE_CONTEXT" | jq -r --arg l "$1" 'if (.languages | index($l)) then "true" else "false" end'; }
        ver()  { echo "$PIPELINE_CONTEXT" | jq -r --arg l "$1" '.versions[$l] // ""'; }

        echo "has_go=$(has go)"           >> "$GITHUB_OUTPUT"
        echo "has_rust=$(has rust)"       >> "$GITHUB_OUTPUT"
        echo "has_node=$(has node)"       >> "$GITHUB_OUTPUT"
        echo "has_python=$(has python)"   >> "$GITHUB_OUTPUT"
        echo "has_java=$(has java)"       >> "$GITHUB_OUTPUT"
        echo "go_version=$(ver go)"       >> "$GITHUB_OUTPUT"
        echo "rust_version=$(ver rust)"   >> "$GITHUB_OUTPUT"
        echo "node_version=$(ver node)"   >> "$GITHUB_OUTPUT"
        echo "python_version=$(ver python)" >> "$GITHUB_OUTPUT"
        echo "java_version=$(ver java)"   >> "$GITHUB_OUTPUT"

    # ── Language toolchain setup (conditional on detected languages) ──────────

    - name: Setup Go
      if: steps.ctx.outputs.has_go == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.ctx.outputs.go_version || '1.24' }}

    - name: Setup Rust
      if: steps.ctx.outputs.has_rust == 'true'
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.ctx.outputs.rust_version || 'stable' }}
        components: rustfmt, clippy

    - name: Setup Node
      if: steps.ctx.outputs.has_node == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.ctx.outputs.node_version || '20' }}

    - name: Setup Python
      if: steps.ctx.outputs.has_python == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.ctx.outputs.python_version || '3.12' }}

    - name: Setup Java
      if: steps.ctx.outputs.has_java == 'true'
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.ctx.outputs.java_version || '17' }}

    # ── pre-commit ────────────────────────────────────────────────────────────

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: Cache pre-commit environments
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-

    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files
