name: 'Octopilot'
description: 'Run Octopilot CLI (op) commands to manage your pipelines.'
inputs:
  command:
    description: 'The command to run (e.g., build, version)'
    required: false
    default: 'help'
  args:
    description: 'Arguments for the command'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/octopilot/octopilot-pipeline-tools/octopilot-pipeline-tools:latest'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - 'echo "DEBUG: GITHUB_WORKSPACE=$GITHUB_WORKSPACE" && echo "DEBUG: Initial pwd=$(pwd)" && ls -la && cd $GITHUB_WORKSPACE && echo "DEBUG: Pwd after cd=$(pwd)" && ls -la && op ${{ inputs.command }} ${{ inputs.args }}'
