name: 'Octopilot Build'
description: 'Build and push container images using Octopilot Pipeline Tools.'
inputs:
  version:
    description: 'Version to build/tag (defaults to ref_name).'
    required: false
    default: ''
  registry:
    description: 'Target registry (e.g. ghcr.io/octopilot).'
    required: true
  platforms:
    description: 'Comma-separated list of platforms to build for (e.g. linux/amd64).'
    required: false
    default: 'linux/amd64'
  op_version:
    description: 'Version of octopilot-pipeline-tools to use.'
    required: false
    default: 'latest'
  sbom_output:
    description: 'Path to output SBOMs.'
    required: false
    default: 'dist/sbom'
  op_binary:
    description: 'Path to op binary (used only when build_bypass is true).'
    required: false
    default: 'op'
  build_bypass:
    description: 'Bypass container execution and run op directly (for bootstrapping).'
    required: false
    default: 'false'
outputs:
  digest:
    description: 'Container image digest.'
    value: ${{ steps.build.outputs.digest }}
runs:
  using: "composite"
  steps:
    - name: Build and Push
      id: build
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_PLATFORMS: ${{ inputs.platforms }}
        INPUT_OP_VERSION: ${{ inputs.op_version }}
        INPUT_SBOM_OUTPUT: ${{ inputs.sbom_output }}
        INPUT_OP_BINARY: ${{ inputs.op_binary }}
        INPUT_BUILD_BYPASS: ${{ inputs.build_bypass }}
      run: |
        # Determine version
        VERSION="${INPUT_VERSION}"
        if [ -z "$VERSION" ]; then
          VERSION="${GITHUB_REF_NAME}"
        fi

        # Create SBOM output directory
        mkdir -p "${INPUT_SBOM_OUTPUT}"

        if [ "${INPUT_BUILD_BYPASS}" == "true" ]; then
            echo "Bypassing container execution. Running op directly..."
            export DOCKER_METADATA_OUTPUT_VERSION="${VERSION}"
            export GITHUB_ACTIONS="true"
            export CI="true"
            
            # Ensure safe directory
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            
            # Ensure op is executable
            chmod +x "${INPUT_OP_BINARY}"
            
            # Run op directly
            "${INPUT_OP_BINARY}" build --repo "${INPUT_REGISTRY}" --platform "${INPUT_PLATFORMS}" --push --sbom-output "${INPUT_SBOM_OUTPUT}"
        else
            # Determine builder image tag
            IMAGE_TAG="${INPUT_OP_VERSION}"
            if [ "${IMAGE_TAG}" == "latest" ]; then
                IMAGE_TAG="latest"
            fi
            
            IMAGE="ghcr.io/octopilot/octopilot-pipeline-tools:${IMAGE_TAG}"
            echo "Using builder image: $IMAGE"

            # Run op build in container
            # Mounts: docker socket, workspace
            # Envs: DOCKER_METADATA_OUTPUT_VERSION, GITHUB_ACTIONS, CI
            docker run --rm \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "$GITHUB_WORKSPACE:/workspace" \
                -w "/workspace" \
                -e DOCKER_METADATA_OUTPUT_VERSION="${VERSION}" \
                -e GITHUB_ACTIONS="true" \
                -e CI="true" \
                --entrypoint /bin/sh \
                "$IMAGE" \
                -c "git config --global --add safe.directory /workspace && op build --repo '${INPUT_REGISTRY}' --platform '${INPUT_PLATFORMS}' --push --sbom-output '${INPUT_SBOM_OUTPUT}'"
        fi

        # Package SBOMs if directory exists and is not empty
        if [ -d "${INPUT_SBOM_OUTPUT}" ] && [ "$(ls -A ${INPUT_SBOM_OUTPUT})" ]; then
            tar -czvf "${INPUT_SBOM_OUTPUT}.tar.gz" -C "${INPUT_SBOM_OUTPUT}" .
        fi

        # Extract digest from the last build entry (application image).
        # builds[0] is typically the base image when skaffold.yaml defines
        # multiple artifacts; the application image is always last by convention.
        if [ -f "build_result.json" ]; then
            TAG=$(jq -r '.builds[-1].tag' build_result.json)
            DIGEST=$(echo "$TAG" | awk -F'@' '{print $2}')
            echo "digest=$DIGEST" >> $GITHUB_OUTPUT
        fi
