name: 'Octopilot'
description: 'Run Octopilot CLI (op) commands to manage your pipelines.'
inputs:
  command:
    description: 'The command to run (e.g., build, version)'
    required: false
    default: 'help'
  args:
    description: 'Arguments for the command'
    required: false
    default: ''
  path:
    description: 'Path to the project (directory containing skaffold.yaml)'
    required: false
    default: '/github/workspace'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/octopilot/octopilot-pipeline-tools/octopilot-pipeline-tools:latest'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - 'cd ${{ inputs.path }} && op ${{ inputs.command }} ${{ inputs.args }}'
