name: 'Is Tag'
description: 'Check if the current commit is a tag (via GITHUB_REF or git describe).'
inputs: {}
outputs:
  is_tag:
    description: 'True if the current commit is a tag, False otherwise.'
    value: ${{ steps.check.outputs.is_tag }}
  tag:
    description: 'The tag name if is_tag is True, empty otherwise.'
    value: ${{ steps.check.outputs.tag }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/octopilot/actions/is-tag:latest'
