name: 'Helm build and push to ttl.sh'
description: >
  Installs Helm (if needed), runs helm dependency build and helm package,
  pushes the chart to oci://ttl.sh/<ttl-uuid>, and writes chart_ref and
  chart_version to an output file for downstream steps.
inputs:
  ttl-uuid:
    description: >
      UUID/name segment for ttl.sh OCI (e.g. from uuidgen). Chart will be
      pushed to oci://ttl.sh/<ttl-uuid>.
    required: true
  chart-path:
    description: >
      Path to the Helm chart directory (relative to workspace root).
    required: false
    default: chart
  output-path:
    description: >
      Path (relative to workspace) to write key=value lines chart_ref and
      chart_version for artifact or downstream use.
    required: false
    default: outputs.txt
  helm-version:
    description: >
      Helm version to install (e.g. v3.16.4). Used only when Helm is installed by this action.
    required: false
    default: v3.16.4

outputs:
  chart_ref:
    description: OCI reference of the pushed chart (e.g. oci://ttl.sh/<uuid>).
  chart_version:
    description: Version of the packaged chart (from Chart.yaml).

runs:
  using: "composite"
  steps:
    - name: Install Helm
      shell: bash
      run: |
        if command -v helm &>/dev/null; then
          echo "Helm already installed: $(helm version --short)"
          exit 0
        fi
        curl -sSL "https://get.helm.sh/helm-${{ inputs['helm-version'] }}-linux-amd64.tar.gz" | tar -xzf - -C /tmp
        sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm
        helm version --short

    - name: Build and push Helm chart to ttl.sh
      shell: bash
      run: |
        set -e
        CHART_OCI_NAME="${{ inputs['ttl-uuid'] }}"
        CHART_PATH="${{ inputs['chart-path'] }}"
        OUT_PATH="${{ inputs['output-path'] }}"
        mkdir -p /tmp/chart-out
        cd "$CHART_PATH"
        helm dependency build .
        helm package . -d /tmp/chart-out
        CHART_TGZ="$(ls /tmp/chart-out/*.tgz | head -1)"
        helm push "$CHART_TGZ" "oci://ttl.sh/${CHART_OCI_NAME}"
        CHART_VERSION="$(helm show chart "$CHART_TGZ" | grep '^version:' | awk '{print $2}')"
        CHART_REF="oci://ttl.sh/${CHART_OCI_NAME}"
        OUT_FILE="${GITHUB_WORKSPACE}/${OUT_PATH}"
        echo "chart_ref=${CHART_REF}" > "$OUT_FILE"
        echo "chart_version=${CHART_VERSION}" >> "$OUT_FILE"
        echo "chart_ref=${CHART_REF}" >> "$GITHUB_OUTPUT"
        echo "chart_version=${CHART_VERSION}" >> "$GITHUB_OUTPUT"
