name: 'kubernetes-auth'
description: 'Authenticate with Kubernetes using OIDC'
inputs:
  oidc_url:
    description: 'OIDC provider URL'
    required: true
  oidc_username:
    description: 'OIDC username (Client ID)'
    required: true
  oidc_password:
    description: 'OIDC password (Client Secret)'
    required: true
  k8s_url:
    description: 'Kubernetes API URL'
    required: true
  k8s_namespace:
    description: 'Default namespace'
    required: false
    default: 'default'
  k8s_skip_tls_verify:
    description: 'Skip TLS verification for Kubernetes API'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/octopilot/actions/kubernetes-auth:latest'
  env:
    INPUT_OIDC_URL: ${{ inputs.oidc_url }}
    INPUT_OIDC_USERNAME: ${{ inputs.oidc_username }}
    INPUT_OIDC_PASSWORD: ${{ inputs.oidc_password }}
    INPUT_K8S_URL: ${{ inputs.k8s_url }}
    INPUT_K8S_NAMESPACE: ${{ inputs.k8s_namespace }}
    INPUT_K8S_SKIP_TLS_VERIFY: ${{ inputs.k8s_skip_tls_verify }}
