name: 'Docker build and push to ttl.sh'
description: >
  Builds an image with docker build, tags it as ttl.sh/<ttl-uuid>-<suffix>:<tag>,
  and pushes to ttl.sh. Use for ephemeral integration images.
  **Deprecated:** Prefer octopilot/actions/octopilot with ttl-uuid for integration;
  it builds from skaffold.yaml and writes build_result.json.
inputs:
  ttl-uuid:
    description: >
      UUID/name segment for ttl.sh (e.g. from uuidgen). Image will be
      ttl.sh/<ttl-uuid>-<suffix>:<tag>.
    required: true
  suffix:
    description: >
      Image name suffix (e.g. monitor). Full image is ttl.sh/<ttl-uuid>-<suffix>:<tag>.
    required: false
    default: monitor
  tag:
    description: Tag for the image (e.g. 1h for ttl.sh TTL).
    required: false
    default: "1h"
  dockerfile:
    description: Path to Dockerfile (relative to context).
    required: false
    default: Dockerfile
  context:
    description: Build context path (e.g. . or path/to/app).
    required: false
    default: "."

outputs:
  image:
    description: Full image reference (e.g. ttl.sh/<uuid>-<suffix>:<tag>).

runs:
  using: "composite"
  steps:
    - name: Build and push image to ttl.sh
      shell: bash
      run: |
        set -e
        IMAGE="ttl.sh/${{ inputs['ttl-uuid'] }}-${{ inputs['suffix'] }}:${{ inputs['tag'] }}"
        docker build -t "$IMAGE" -f "${{ inputs['dockerfile'] }}" "${{ inputs['context'] }}"
        docker push "$IMAGE"
        echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
