name: 'Integration build one artifact'
description: >
  Builds one integration matrix item (image via docker or pack, or chart via helm)
  and writes key=value output(s) to a file for the workflow to upload.
inputs:
  artifact:
    description: 'JSON object for one matrix item (type, build_method, context, suffix, output_key, path?, dockerfile?, builder?, build_env?)'
    required: true
  ttl-uuid:
    description: 'UUID for ttl.sh image/chart naming'
    required: true
  output-path:
    description: 'Path to write key=value lines (e.g. outputs.txt)'
    required: false
    default: outputs.txt
  op_version:
    description: 'Op image version (e.g. v1.0.4).'
    required: false
    default: v1.0.4
runs:
  using: "composite"
  steps:
    - name: Parse artifact
      id: parse
      shell: bash
      env:
        ARTIFACT: ${{ inputs.artifact }}
      run: |
        set -e
        echo "type=$(echo "$ARTIFACT" | jq -r '.type // ""')" >> "$GITHUB_OUTPUT"
        echo "build_method=$(echo "$ARTIFACT" | jq -r '.build_method // ""')" >> "$GITHUB_OUTPUT"
        echo "context=$(echo "$ARTIFACT" | jq -r '.context // "."')" >> "$GITHUB_OUTPUT"
        echo "suffix=$(echo "$ARTIFACT" | jq -r '.suffix // ""')" >> "$GITHUB_OUTPUT"
        echo "output_key=$(echo "$ARTIFACT" | jq -r '.output_key // ""')" >> "$GITHUB_OUTPUT"
        echo "image=$(echo "$ARTIFACT" | jq -r '.image // ""')" >> "$GITHUB_OUTPUT"
        echo "path=$(echo "$ARTIFACT" | jq -r '.path // ""')" >> "$GITHUB_OUTPUT"
        echo "dockerfile=$(echo "$ARTIFACT" | jq -r '.dockerfile // "Dockerfile"')" >> "$GITHUB_OUTPUT"
        echo "builder=$(echo "$ARTIFACT" | jq -r '.builder // "paketobuildpacks/builder-jammy-base"')" >> "$GITHUB_OUTPUT"
        echo "build_env=$(echo "$ARTIFACT" | jq -r '.build_env // ""')" >> "$GITHUB_OUTPUT"

    - name: Build and push image (Octopilot)
      id: build
      if: steps.parse.outputs.type == 'image'
      uses: octopilot/actions/octopilot@main
      with:
        ttl-uuid: ${{ inputs.ttl-uuid }}
        ttl-tag: '1h'
        artifact: ${{ steps.parse.outputs.image }}
        op_version: ${{ inputs.op_version }}

    - name: Build and push chart (Octopilot)
      id: chart_build
      if: steps.parse.outputs.type == 'chart' && steps.parse.outputs.image != ''
      uses: octopilot/actions/octopilot@main
      with:
        ttl-uuid: ${{ inputs.ttl-uuid }}
        ttl-tag: '1h'
        artifact: ${{ steps.parse.outputs.image }}
        op_version: ${{ inputs.op_version }}

    - name: Chart requires skaffold artifact
      if: steps.parse.outputs.type == 'chart' && steps.parse.outputs.image == ''
      shell: bash
      run: |
        echo "::error::Chart build via Octopilot requires the chart to be defined in skaffold build.artifacts (with matching context). Add the chart as an artifact or use a repo where the chart is built by skaffold."
        exit 1

    - name: Write image output file
      if: steps.parse.outputs.type == 'image'
      shell: bash
      run: |
        echo "${{ steps.parse.outputs.output_key }}=${{ steps.build.outputs.tag }}" > "${{ inputs.output-path }}"

    - name: Write chart output file
      if: steps.parse.outputs.type == 'chart' && steps.parse.outputs.image != ''
      shell: bash
      run: |
        echo "${{ steps.parse.outputs.output_key }}=${{ steps.chart_build.outputs.tag }}" > "${{ inputs.output-path }}"
